version: "3"

vars:
  BINARY_NAME: tflint-ruleset-modularity
  MAIN_PACKAGE: .
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "none"
  DATE:
    sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
  LDFLAGS: -s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}} -X main.date={{.DATE}}

includes:
  setup:
    taskfile: ./taskfiles/setup.yml
  build:
    taskfile: ./taskfiles/build.yml
  test:
    taskfile: ./taskfiles/test.yml
  lint:
    taskfile: ./taskfiles/lint.yml
  release:
    taskfile: ./taskfiles/release.yml
  ci:
    taskfile: ./taskfiles/ci.yml

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
